apiVersion: v2
appVersion: 0.0.1
name: n8n
description: A Helm chart for n8n official chart
home: https://github.com/giantswarm/n8n
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/light.svg
sources:
- https://github.com/community-charts/helm-charts
version: 0.0.0-dev
annotations:
  application.giantswarm.io/team: team-planeteers
dependencies:
  - name: redis
    version: 20.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.4.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
